[package]
name = "password_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
block-modes = "0.9.1"
pbkdf2 = { version = "0.12" }
sha2 = "0.10"
rand = "0.8"
aes-gcm = "0.10.3"
serde_json = "1.0"